---
- name: Install Apache on RedHat
  ansible.builtin.dnf:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Apache on Debian
  ansible.builtin.apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"

- name: Enable & start Apache on Debian
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  become: true
  when: ansible_os_family == "Debian"

- name: Enable & start Apache on Redhat
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
  become: true
  when: ansible_os_family == "RedHat"
