---
- name: Install and configure Apache on RedHat systems
  hosts: webservers
  become: true
  tasks:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Enable & start Apache on Redhat
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
