---
collections:
  - name: collections/ansible_collections/myorg/unix/
    type: dir
  - name: collections/ansible_collections/myorg/toolchain/
    type: dir
  - name: collections/ansible_collections/myorg/publicapi/
    type: git
    source: https://github.com/rstyczynski/ansible-collection-howto.git#/collections/ansible_collections/myorg/publicapi
    version: main
