---
collections:
  - name: collections/ansible_collections/myorg/unix/
    type: dir
  - name: collections/ansible_collections/myorg/toolchain/
    type: dir
  - name: collections/ansible_collections/myorg/publicapi/
    type: dir