---
ansible:
  cfg:
    defaults:
      deprecation_warnings: false

dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: ubuntu
    image: ubuntu:22.04
    pre_build_image: false
    dockerfile: Dockerfile
    groups: [webservers]

provisioner:
  name: ansible
  playbooks:
    converge: ../../apache1_debian.yml

verifier:
  name: ansible
