---
- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Install httpd
  ansible.builtin.dnf:
    name: httpd
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Enable & start Apache on Debian
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  become: true
  when: ansible_os_family == "Debian"

- name: Enable & start Apache on Redhat
  ansible.builtin.service:
    name: httpd
    enabled: true
    state: started
  become: true
  when: ansible_os_family == "RedHat"
