---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    # === Package Block ===
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: "TEST_CASE: Verify Apache package is installed on RedHat"
      ansible.builtin.assert:
        that:
          - "'httpd' in ansible_facts.packages"
        fail_msg: "Apache (httpd) package is not installed on RedHat system"
      when: ansible_os_family == "RedHat"

    - name: "TEST_CASE: Verify Apache package is installed on Debian"
      ansible.builtin.assert:
        that:
          - "'apache2' in ansible_facts.packages"
        fail_msg: "Apache (apache2) package is not installed on Debian system"
      when: ansible_os_family == "Debian"

    # === Service Block ===
    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: "TEST_CASE: Assert httpd service is running on RedHat"
      ansible.builtin.assert:
        that:
          - "'httpd' in ansible_facts.services or 'httpd.service' in ansible_facts.services"
          - "ansible_facts.services.get('httpd.service').state == 'running'"
        fail_msg: "Apache (httpd) service is not running on RedHat system"
        success_msg: "Apache (httpd) service is running on RedHat system"
      when: ansible_os_family == "RedHat"

    - name: "TEST_CASE: Assert apache2 service is running on Debian"
      ansible.builtin.assert:
        that:
          - "'apache2' in ansible_facts.services"
          - "ansible_facts.services['apache2'].state == 'running'"
        fail_msg: "Apache (apache2) service is not running on Debian system"
        success_msg: "Apache (apache2) service is running on Debian system"
      when: ansible_os_family == "Debian"

    # === TCP Block ===
    - name: "TEST_CASE: Check if port 80 is open (Apache)"
      ansible.builtin.wait_for:
        port: 80
        host: "{{ ansible_default_ipv4.address | default('127.0.0.1') }}"
        state: started
        timeout: 5
      register: apache_port_check

    - name: "TEST_CASE: Assert port 80 is accessible"
      ansible.builtin.assert:
        that:
          - apache_port_check.state == "started"
        fail_msg: "Port 80 is not accessible"
        success_msg: "Port 80 is accessible"
